[package]
name = "learning-management-integration-contract"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }

# Optimization settings for production builds
[profile.release]
opt-level = 'z'  # Optimize for size (important for contract deployment)
overflow-checks = true
debug = 0
strip = true
debug-assertions = false
panic = 'abort'
codegen-units = 1
lto = true

# Test profile for faster compilation during development
[profile.test]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

# Soroban snapshot configuration
[package.metadata.soroban]
generate-snapshots = false
snapshot-dir = "test_snapshots"
verbose-snapshots = false
