import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';
import { ClientLayout } from '@/components/layouts/ClientLayout';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={GeistSans.className}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
